apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml -o export/
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: drkiq
  name: drkiq
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: drkiq
    spec:
      containers:
      - image: sherifkhedr/drkiq:tag
        name: drkiq
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: config-env
        resources: {}
        volumeMounts:
        - mountPath: /drkiqs
          name: drkiq-sherif
      restartPolicy: Always
      volumes:
      - name: drkiq-sherif
        persistentVolumeClaim:
          claimName: drkiq-sherif
status: {}
