apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -v convert -f docker-compose.yml -o export
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: drkiq
  name: drkiq
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    io.kompose.service: drkiq
status:
  loadBalancer: {}
