apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -v convert -f docker-compose.yml -o export
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: redis
status:
  loadBalancer: {}
