version: "2"

services:
  postgres:
    image: postgres:9.4.5
    environment:
      POSTGRES_USER: drkiq
      POSTGRES_PASSWORD: yourpassword
    ports:
      - '5432:5432'
    volumes:
      - drkiq-postgres:/var/lib/postgresql/data

  redis:
    image: redis:3.0.5
    ports:
      - '6379:6379'
    volumes:
      - drkiq-redis:/var/lib/redis/data

  drkiq:
    build: .
    image: sherifkhedr/drkiq:tag
    links:
      - postgres
      - redis
    volumes:
      - drkiq-sherif:/drkiqs
    ports:
      - '8000:8000'
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    image: sherifkhedr/sidekiq:tag
    links:
      - postgres
      - redis
    volumes:
      - drkiq-sherif:/drkiqs
